---
abstract: 'Create your own op trees.'
author:
  - "Simon Cozens, C<simon@cpan.org>\n(Who else?)"
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Generate
no_index:
  package: B::OP
provides:
  B::Generate:
    file: lib/B/Generate.pm
    version: 1.27
  B::OP:
    file: lib/B/Generate.pm
requires:
  B: 1.09
  ExtUtils::CBuilder: 0
  Module::Build: 0
  perl: 5.005062
resources:
  license: http://dev.perl.org/licenses/
version: 1.27
