# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         B-Generate
version:      1.42
version_from: lib/B/Generate.pm
installdirs:  site
requires:
    B:                             0
    ExtUtils::CBuilder:            0
    ExtUtils::Embed:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
