---
name: B-Generate
version: 1.15
author:
  - |-
    Simon Cozens, C<simon@cpan.org>
    (Who else?)
abstract: Create your own op trees.
license: perl
requires:
  B: 1.09
  ExtUtils::CBuilder: 0
  Module::Build: 0
  perl: 5.5.62
dynamic_config: 0
provides:
  B::Generate:
    file: lib/B/Generate.pm
    version: 1.15
  B::OP:
    file: lib/B/Generate.pm
    version: 1.15
generated_by: Module::Build version 0.2612
