--- #YAML:1.0
name:               B-Generate
version:            1.30
abstract:           Create your own op trees.
author:
    - Simon Cozens
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B:                   1.09
    ExtUtils::CBuilder:  0
    Module::Build:       0
resources:
    license:      http://dev.perl.org/licenses/
    MailingList:  mailto:"600 subscribers" <perl5-porters@perl.org>
    repository:   http://github.com/rurban/b-generate
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5601
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
